Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/FirstParameterIndentation:
  Enabled: false

Style/IndentArray:
  Enabled: false

Layout/TrailingBlankLines:
  Enabled: false
